# Generated by Django 4.2.14 on 2025-12-08 14:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeOSM',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('osm_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('amenity', models.CharField(blank=True, max_length=100, null=True)),
                ('addr_city', models.CharField(blank=True, max_length=100, null=True)),
                ('addr_street', models.CharField(blank=True, max_length=200, null=True)),
                ('addr_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(db_column='wkb_geometry', srid=4326)),
            ],
            options={
                'db_table': 'cafes_osm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('ogc_fid', models.IntegerField(db_column='ogc_fid', primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(db_column='geometry', srid=4326)),
                ('co_id', models.CharField(db_column='co_id', max_length=20, null=True)),
                ('countyname', models.CharField(db_column='countyname', max_length=200, null=True)),
                ('english', models.CharField(db_column='english', max_length=200, null=True)),
                ('scribes', models.CharField(db_column='scribes', max_length=10, null=True)),
                ('gaeilge', models.CharField(db_column='gaeilge', max_length=200, null=True)),
                ('logainm_id', models.CharField(db_column='logainm_id', max_length=20, null=True)),
                ('guid', models.CharField(db_column='guid', max_length=100, null=True)),
                ('contae', models.CharField(db_column='contae', max_length=200, null=True)),
                ('county', models.CharField(db_column='county', max_length=200, null=True)),
                ('province', models.CharField(db_column='province', max_length=50, null=True)),
                ('centroid_x', models.FloatField(db_column='centroid_x', null=True)),
                ('centroid_y', models.FloatField(db_column='centroid_y', null=True)),
                ('area', models.FloatField(db_column='area', null=True)),
                ('objectid', models.IntegerField(db_column='objectid', null=True)),
                ('shape_area', models.FloatField(db_column='shape__area', null=True)),
                ('shape_length', models.FloatField(db_column='shape__length', null=True)),
            ],
            options={
                'db_table': 'counties',
                'managed': True,
            },
        ),
    ]
