# Generated by Django 4.2.14 on 2025-11-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0002_quarter'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cafe',
            index=models.Index(fields=['location'], name='cafe_location_gist', opclasses=['gist']),
        ),
    ]
