# Generated by Django 4.2.14 on 2025-11-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0003_cafe_cafe_location_gist'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quarter',
            index=models.Index(fields=['boundary'], name='quarter_boundary_gist', opclasses=['gist']),
        ),
    ]
