# Generated by Django 4.2.14 on 2025-12-08 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0006_cafeosm_county_delete_cafe_delete_quarter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafeosm',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='county',
            options={'managed': True},
        ),
    ]
